spring:
  application:
    name=movie-seat-reservation
  datasource :
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myTheater
    username: root
    password:
  jpa:
    show-sql: true

  management:
    endpoints:
      web:
        base-path: /demo
        exposure:
          include: prometheus